# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FRD',
                'doc_host': 'https://BenAbramowitz.github.io',
                'git_url': 'https://github.com/BenAbramowitz/FRD',
                'lib_path': 'FRD'},
  'syms': {'FRD.core': {'FRD.core.foo': ('core.html#foo', 'FRD/core.py')}}}
